# Server
server:
  port: 8000

spring:
  # DB
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456

# mybatis
mybatis:
  type-aliases-package: com.kunlinr.mybatis.entity
  mapperLocations: classpath:mappers/*.xml